### ISSUE TITLE
运行test.py报错

### ISSUE THREAD

**Issue by Lamchi-Joo** [2833844911/Gesture_recognition_captcha#1]
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 280, 3, 176] to have 3 channels, but got 280 channels instead

**Comment by 2833844911** [comment]
opencv 的版本opencv_python_headless==4.7.0.72 需要这个，你的应该不一样

**Comment by Lamchi-Joo** [comment]
是一样的，是不是scikit-image的问题，我目前的版本是0.19.3

**Comment by 2833844911** [comment]
df2 = cv2.imread(path)
image = cv2.resize(df2, (280, 176))
transform = transforms.Compose([
    transforms.ToTensor()
])(image).to(device)
image = torch.permute(transform, (2, 0, 1)).unsqueeze(dim=0)

影响不大
torch.permute(transform, (2, 0, 1))
这里交换维度 改为
torch.permute(transform, (0, 1, 2))
就可以了
你的cv2读取和我的不一样

**Comment by 2833844911** [comment]
问题有解决吗

**Comment by Lamchi-Joo** [comment]
可以了，解决了，谢谢老哥
